import type { Metadata } from "next";
import "./globals.css";
import dynamic from "next/dynamic";
import { draftMode } from "next/headers";
import { token } from "@/lib/sanity/fetch";
import { Inter as FontSans } from "next/font/google";
import { ThemeProvider } from "@/components/ThemeProvider";
import Navbar from "@/components/Navbar";
import { cn } from "@/lib/utils";
import Footer from "@/components/Footer";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
const PreviewProvider = dynamic(() => import("@/components/PreviewProvider"));

export const metadata: Metadata = {
  title: "Charles Schwab",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {draftMode().isEnabled ? (
            <PreviewProvider token={token}>{children}</PreviewProvider>
          ) : (
            children
          )}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
