import type { Metadata } from "next";
import "./globals.css";
import { draftMode } from "next/headers";
import { Inter as FontSans } from "next/font/google";
import { ThemeProvider } from "@/components/layout/theme-provider";
import Navbar from "@/components/layout/navbar";
import { cn } from "@/lib/utils";
import Footer from "@/components/layout/footer";
import { VisualEditing } from "@/components/layout/visual-editing";
import GSAPProvider from "@/components/layout/gsap-provider";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Charles Schwab",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <GSAPProvider>
            <Navbar />
            {children}
            {draftMode().isEnabled && <VisualEditing />}
            <Footer />
          </GSAPProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
