name: Deploy sanity studio
on:
  push:
    branches: [main]
    paths:
      - sanity/**
jobs:
  # Deploy job
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sanity
    # Secrets stored in GitHub repo settings
    env:
      SANITY_AUTH_TOKEN: ${{ secrets.SANITY_DEPLOY_TOKEN }}
      SANITY_STUDIO_PREVIEW_URL: ${{ secrets.SANITY_STUDIO_PREVIEW_URL}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: npm
          # Doesn't respect working-directory above so pass full path
          cache-dependency-path: sanity/package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Deploy to Sanity
        run: npm run deploy
